"""
declarative

Revision ID: f66f268b9ddc
Revises: 622fd3c852ed
Create Date: 2024-08-06 10:53:13.516124

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from tarka.utility.envvar import parse_bool_envvar


# revision identifiers, used by Alembic.
revision: str = 'f66f268b9ddc'
down_revision: Union[str, None] = '622fd3c852ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ext_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thing_ext_id'), 'thing', ['ext_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    if not parse_bool_envvar("TARKA_DB_MIGRATION_FORCE_DOWNGRADE"):
        raise Exception(
            "Downgrading through this migration may permanently drop critical data\n"
            "set 'TARKA_DB_MIGRATION_FORCE_DOWNGRADE' env-var to '1' to do it anyway"
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thing_ext_id'), table_name='thing')
    op.drop_table('thing')
    # ### end Alembic commands ###
