"""
scalars

Revision ID: 622fd3c852ed
Revises: 84c018bb80b5
Create Date: 2024-05-15 18:37:21.346764

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from tarka.utility.envvar import parse_bool_envvar

# revision identifiers, used by Alembic.
revision: str = "622fd3c852ed"
down_revision: Union[str, None] = "84c018bb80b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("int0", sa.BigInteger(), nullable=True))
    op.drop_column("users", "str1")
    # ### end Alembic commands ###


def downgrade() -> None:
    if not parse_bool_envvar("TARKA_DB_MIGRATION_FORCE_DOWNGRADE"):
        raise Exception(
            "Downgrading through this migration may permanently drop critical data\n"
            "set 'TARKA_DB_MIGRATION_FORCE_DOWNGRADE' env-var to '1' to do it anyway"
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("str1", sa.VARCHAR(), nullable=True))
    op.drop_column("users", "int0")
    # ### end Alembic commands ###
