"""
users

Revision ID: 84c018bb80b5
Revises: a9d481fef0bd
Create Date: 2024-05-15 18:35:43.444238

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from tarka.asqla.types import UTCDateTime
from tarka.utility.envvar import parse_bool_envvar

# revision identifiers, used by Alembic.
revision: str = "84c018bb80b5"
down_revision: Union[str, None] = "a9d481fef0bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ext_id", sa.Integer(), nullable=False),
        sa.Column("str0", sa.String(), nullable=True),
        sa.Column("str1", sa.String(), nullable=True),
        sa.Column("utc0", UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_ext_id"), "users", ["ext_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    if not parse_bool_envvar("TARKA_DB_MIGRATION_FORCE_DOWNGRADE"):
        raise Exception(
            "Downgrading through this migration may permanently drop critical data\n"
            "set 'TARKA_DB_MIGRATION_FORCE_DOWNGRADE' env-var to '1' to do it anyway"
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_ext_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
